In [1]:
import numpy as np

In [2]:
X = np.array(([2,9],[1,5],[3,6]),dtype=float)
Y = np.array(([92],[86],[89]))


In [3]:
X = X/np.amax(X,axis=0)
Y = Y/100

In [4]:
print(X)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]


In [5]:
print(Y)

[[0.92]
 [0.86]
 [0.89]]


In [6]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
def derivatives_sigmoid(x):
    return x*(1-x)

In [7]:
epoch = 7000
learning_rate = 0.25
inputlayer_neurons = 2
hiddenlayer_neurons = 3
output_neurons = 1

In [9]:
wh = np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
print(wh)
bh = np.random.uniform(size=(1,hiddenlayer_neurons))
print(bh)

[[0.55682938 0.68374996 0.06650186]
 [0.32149447 0.03139366 0.99231733]]
[[0.93296561 0.2702768  0.81753279]]


In [10]:
wout = np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
print(wout)
bout = np.random.uniform(size=(1,output_neurons))
print(bout)

[[0.95351274]
 [0.28680407]
 [0.0268874 ]]
[[0.34559299]]


In [13]:
for i in range(epoch):
    hinp1 = np.dot(X,wh)
    hinp = hinp1+bh
    hlayer_act = sigmoid(hinp)
    outinp1 = np.dot(hlayer_act,wout)
    outinp = outinp1+bout
    output = sigmoid(outinp)
    EO = Y - output
    outgrad = derivatives_sigmoid(output)
    d_output = EO*outgrad
    EH = d_output.dot(wout.T)
    hiddengrad = derivatives_sigmoid(hlayer_act)
    d_hiddenlayer = EH*hiddengrad
    wout += hlayer_act.T.dot(d_output)* learning_rate
    wh += X.T.dot(d_hiddenlayer)*learning_rate

In [14]:
print("Input = \n"+str(X))

Input = 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]


In [15]:
print("Actual Output:\n"+str(Y))

Actual Output:
[[0.92]
 [0.86]
 [0.89]]


In [16]:
print("Predicted Output:\n"+str(output))

Predicted Output:
[[0.89421261]
 [0.88023239]
 [0.89521837]]
